### ISSUE TITLE
Please update showcase page

### ISSUE THREAD

**Issue by tyohan** [MyanmarAPI/election-website#1]
We need to update showcase page and show to user so they can upload their apps.

**Comment by nyanlynnhtut** [comment]
@tyohan Are you allow to upload their app data (include screenshots) by user? Which data are requirement?

**Comment by tyohan** [comment]
@nyanlynnhtut I think we need 
- title
- description
- app icon
- screen shot (at least 2)
- Google play url
- APK (for direct download)
- URL for website

**Comment by tyohan** [comment]
@nyanlynnhtut we need all information in Burmese. I will ask Ye Lin Aung to create a content how to download in Burmese too so we can add on this page.

Make sure each app has their own URL like http://maepaysoh.org/showcase/electroscope so we can easily promote each app directly

**Comment by nyanlynnhtut** [comment]
@tyohan Are you want to control the showcase app publish approved by admin?

**Comment by tyohan** [comment]
@nyanlynnhtut Yes I think we need to control it, just make a simple like approve or not. But by default it will be approved. But if we found there is a unappropriate content then we can take it down.

**Comment by nyanlynnhtut** [comment]
@tyohan I think, some of application are same name? How we can make showcase url?
eg:  
http://maepaysoh.org/showcase/electroscope
http://maepaysoh.org/showcase/electroscope-2

**Comment by tyohan** [comment]
@nyanlynnhtut let them input their own slug, but we can auto generate it from app name. Just like WordPress work

**Comment by nyanlynnhtut** [comment]
@tyohan This is now ready on maepaysoh website.
